apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.app.name }}
spec:
  host: {{ .Values.route.host }}
  path: {{ .Values.route.path}}
  to:
    kind: Service
    name: {{ .Values.app.name }}-service
  port:
    targetPort: 8079
  tls:
    termination: edge
