apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.app.name }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ .Values.app.name }}-service
  port:
    targetPort: 8080
  tls:
    termination: edge
